---
 - hosts: web
   tasks:
      - name: Install web service
        yum:
           name: httpd
           state: present
      - name: Start Web server
        service:
            name: httpd
            state: started

